import { StyleSheet, Platform, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

const styles = StyleSheet.create({
  modeToggleRow: {
    flexDirection: 'row',
    backgroundColor: 'rgba(255, 255, 255, 0.03)',
    borderRadius: 12,
    padding: 4,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.05)',
  },
  modeToggleBtn: {
    flex: 1,
    paddingVertical: 10,
    alignItems: 'center',
    borderRadius: 8,
  },
  modeToggleBtnActive: {
    backgroundColor: '#1E293B',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
  },
  modeToggleText: {
    color: '#94A3B8',
    fontSize: 12,
    fontWeight: '600',
  },
  modeToggleTextActive: {
    color: '#FFFFFF',
  },
  scanActionBtn: {
    backgroundColor: '#3B82F6',
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  scanActionBtnText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: 'bold',
  },
  scanningLabel: {
    color: '#94A3B8',
    fontSize: 13,
  },
  noDevicesText: {
    color: '#64748B',
    fontSize: 12,
    textAlign: 'center',
    marginVertical: 12,
  },
  bleDeviceItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.01)',
    borderRadius: 10,
    padding: 12,
    marginTop: 8,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.03)',
  },
  bleDeviceNameText: {
    color: '#F8FAFC',
    fontSize: 13,
    fontWeight: 'bold',
  },
  bleDeviceIdText: {
    color: '#64748B',
    fontSize: 11,
    marginTop: 2,
  },
  bleDeviceConnectBtn: {
    backgroundColor: 'rgba(59, 130, 246, 0.15)',
    borderColor: '#3B82F6',
    borderWidth: 1,
    borderRadius: 6,
    paddingVertical: 6,
    paddingHorizontal: 12,
  },
  bleDeviceConnectText: {
    color: '#3B82F6',
    fontSize: 12,
    fontWeight: 'bold',
  },
  connectingLabel: {
    color: '#94A3B8',
    fontSize: 14,
  },
  connectedDeviceLabel: {
    color: '#10B981',
    fontSize: 14,
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 4,
  },
  connectedDeviceIdText: {
    color: '#64748B',
    fontSize: 12,
    textAlign: 'center',
    marginBottom: 8,
  },
  errorAlert: {
    backgroundColor: 'rgba(239, 68, 68, 0.1)',
    borderColor: '#EF4444',
    borderWidth: 1,
    borderRadius: 10,
    padding: 10,
    marginBottom: 12,
  },
  errorAlertText: {
    color: '#EF4444',
    fontSize: 12,
    fontWeight: '600',
  },
  floatingWarning: {
    position: 'absolute',
    top: Platform.OS === 'ios' ? 60 : 30,
    left: 16,
    right: 16,
    zIndex: 9999,
    backgroundColor: '#EF4444',
    borderRadius: 10,
    padding: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 10,
    borderWidth: 1,
    borderColor: '#F87171',
  },
  floatingWarningText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '600',
    textAlign: 'center',
  },
  mainContainer: {
    flex: 1,
    backgroundColor: '#070A13',
  },
  scrollContent: {
    padding: 16,
    paddingBottom: 40,
  },
  glassHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.03)',
    borderColor: 'rgba(255, 255, 255, 0.08)',
    borderWidth: 1,
    borderRadius: 16,
    padding: 16,
    marginTop: 20,
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  rowBetween: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  statusRing: {
    width: 10,
    height: 10,
    borderRadius: 5,
    marginRight: 8,
  },
  titleText: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#FFFFFF',
  },
  batteryText: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#10B981',
  },
  alignRight: {
    alignItems: 'flex-end',
  },
  miniStatsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 8,
    paddingVertical: 12,
  },
  miniStat: {
    color: '#94A3B8',
    fontSize: 12,
  },
  card: {
    backgroundColor: 'rgba(255, 255, 255, 0.02)',
    borderColor: 'rgba(255, 255, 255, 0.05)',
    borderWidth: 1,
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
  },
  cardTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#F8FAFC',
    marginBottom: 12,
  },
  subtext: {
    color: '#64748B',
    fontSize: 12,
    marginBottom: 4,
  },
  gaugeContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    height: 180,
  },
  gaugeCenterText: {
    position: 'absolute',
    alignItems: 'center',
  },
  gaugeScoreText: {
    fontSize: 32,
    fontWeight: 'bold',
    color: '#FFFFFF',
  },
  gaugeLevelText: {
    fontSize: 14,
    fontWeight: '600',
    marginTop: 4,
  },
  gaugeActionText: {
    color: '#94A3B8',
    fontSize: 13,
    textAlign: 'center',
    marginTop: 4,
    marginBottom: 16,
  },
  multiplierList: {
    backgroundColor: 'rgba(255, 255, 255, 0.01)',
    borderRadius: 12,
    padding: 12,
  },
  multiplierItem: {
    color: '#64748B',
    fontSize: 12,
    marginBottom: 6,
  },
  sectionLabel: {
    color: '#94A3B8',
    fontSize: 13,
    fontWeight: '600',
    marginTop: 12,
    marginBottom: 8,
  },
  segmentBtn: {
    flex: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.02)',
    borderColor: 'rgba(255, 255, 255, 0.05)',
    borderWidth: 1,
    borderRadius: 8,
    paddingVertical: 10,
    alignItems: 'center',
    marginRight: 6,
  },
  segmentBtnActive: {
    backgroundColor: '#3B82F6',
    borderColor: '#3B82F6',
  },
  segmentBtnText: {
    color: '#64748B',
    fontSize: 11,
    fontWeight: '600',
  },
  segmentBtnTextActive: {
    color: '#FFFFFF',
  },
  toggleBtn: {
    backgroundColor: 'rgba(255, 255, 255, 0.02)',
    borderColor: 'rgba(255, 255, 255, 0.05)',
    borderWidth: 1,
    borderRadius: 8,
    paddingVertical: 6,
    paddingHorizontal: 12,
  },
  toggleBtnActive: {
    backgroundColor: 'rgba(239, 68, 68, 0.2)',
    borderColor: '#EF4444',
  },
  toggleBtnText: {
    color: '#F8FAFC',
    fontSize: 12,
    fontWeight: 'bold',
  },
  simulationGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginTop: 8,
  },
  simBtn: {
    width: '48%',
    backgroundColor: 'rgba(255, 255, 255, 0.02)',
    borderLeftWidth: 4,
    borderRadius: 8,
    padding: 12,
    marginBottom: 10,
  },
  simBtnText: {
    color: '#F8FAFC',
    fontSize: 12,
    fontWeight: '600',
  },
  calibrateLargeBtn: {
    backgroundColor: 'rgba(59, 130, 246, 0.15)',
    borderColor: '#3B82F6',
    borderWidth: 1.5,
    borderRadius: 16,
    padding: 16,
    alignItems: 'center',
    marginBottom: 16,
  },
  calibrateLargeBtnText: {
    color: '#3B82F6',
    fontSize: 14,
    fontWeight: 'bold',
  },
  contactItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.01)',
    borderRadius: 12,
    padding: 12,
    marginBottom: 8,
  },
  contactName: {
    color: '#F8FAFC',
    fontSize: 13,
    fontWeight: 'bold',
  },
  contactPhone: {
    color: '#64748B',
    fontSize: 11,
    marginTop: 2,
  },
  notifyBadge: {
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    color: '#F8FAFC',
    fontSize: 10,
    fontWeight: 'bold',
    paddingVertical: 4,
    paddingHorizontal: 8,
    borderRadius: 6,
  },
  linkText: {
    color: '#3B82F6',
    fontSize: 13,
    fontWeight: '600',
  },
  graphContainer: {
    height: 140,
    marginVertical: 12,
    backgroundColor: 'rgba(0, 0, 0, 0.2)',
    borderRadius: 12,
  },
  thresholdTextLabel: {
    fill: '#EF4444',
    fontSize: 10,
    x: 10,
    y: 65,
  },
  graphLegendPin: {
    width: 8,
    height: 8,
    borderRadius: 4,
    marginRight: 6,
  },
  legendText: {
    color: '#64748B',
    fontSize: 11,
  },
  overlayBg: {
    flex: 1,
    backgroundColor: '#7F1D1D',
    justifyContent: 'center',
  },
  overlayBgFlash: {
    backgroundColor: '#B91C1C',
  },
  overlayContainer: {
    alignItems: 'center',
    padding: 24,
  },
  alignCenter: {
    alignItems: 'center',
  },
  overlayAlertHeader: {
    color: '#FFFFFF',
    fontSize: 28,
    fontWeight: '900',
    textAlign: 'center',
    marginBottom: 8,
  },
  overlaySubheader: {
    color: '#FCA5A5',
    fontSize: 16,
    textAlign: 'center',
    marginBottom: 24,
  },
  countdownWrapper: {
    width: 160,
    height: 160,
    borderRadius: 80,
    borderWidth: 6,
    borderColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical: 24,
  },
  countdownNum: {
    color: '#FFFFFF',
    fontSize: 54,
    fontWeight: 'bold',
  },
  countdownSec: {
    color: '#FCA5A5',
    fontSize: 12,
    fontWeight: 'bold',
    marginTop: -4,
  },
  alertExplanation: {
    color: '#FEE2E2',
    textAlign: 'center',
    fontSize: 14,
    lineHeight: 22,
    marginHorizontal: 16,
    marginBottom: 32,
  },
  cancelBtn: {
    backgroundColor: '#EF4444',
    borderColor: '#FFFFFF',
    borderWidth: 2,
    borderRadius: 16,
    paddingVertical: 16,
    paddingHorizontal: 32,
    width: width - 80,
    alignItems: 'center',
    marginBottom: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
  },
  cancelBtnText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: 'bold',
  },
  helpNowBtn: {
    backgroundColor: 'transparent',
    paddingVertical: 12,
  },
  helpNowBtnText: {
    color: '#FECACA',
    fontSize: 14,
    textDecorationLine: 'underline',
    fontWeight: '600',
  },
  dispatchedCircle: {
    width: 140,
    height: 140,
    borderRadius: 70,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical: 32,
  },
  dispatchedIcon: {
    fontSize: 60,
  },
  dispatchedSubheader: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 16,
  },
  dispatchReportCard: {
    backgroundColor: 'rgba(0, 0, 0, 0.2)',
    borderRadius: 16,
    padding: 16,
    width: width - 48,
    marginBottom: 32,
  },
  reportItem: {
    color: '#FECACA',
    fontSize: 13,
    marginBottom: 8,
    lineHeight: 18,
  },
  terminalCard: {
    marginHorizontal: 16,
    marginBottom: 24,
    borderRadius: 18,
    backgroundColor: '#0D1117',
    borderWidth: 1,
    borderColor: '#21262D',
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.45,
    shadowRadius: 12,
    elevation: 8,
  },
  terminalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: '#161B22',
    borderBottomWidth: 1,
    borderBottomColor: '#21262D',
  },
  terminalTitle: {
    color: '#E6EDF3',
    fontSize: 15,
    fontWeight: '700',
    letterSpacing: 0.3,
    marginRight: 8,
  },
  terminalBadge: {
    backgroundColor: '#21262D',
    borderRadius: 10,
    paddingHorizontal: 7,
    paddingVertical: 2,
  },
  terminalBadgeText: {
    color: '#8B949E',
    fontSize: 11,
    fontWeight: '600',
  },
  terminalClearBtn: {
    marginRight: 12,
    backgroundColor: '#21262D',
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  terminalClearBtnText: {
    color: '#EF4444',
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  terminalChevron: {
    color: '#8B949E',
    fontSize: 13,
    fontWeight: '700',
  },
  terminalChipRow: {
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#21262D',
  },
  terminalChip: {
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#30363D',
    paddingHorizontal: 12,
    paddingVertical: 5,
    marginRight: 6,
    backgroundColor: 'transparent',
  },
  terminalChipText: {
    color: '#8B949E',
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  terminalScrollArea: {
    maxHeight: 320,
    paddingHorizontal: 12,
    paddingTop: 6,
    paddingBottom: 8,
  },
  terminalLogRow: {
    marginBottom: 5,
    flexDirection: 'column',
  },
  terminalLogTime: {
    fontSize: 10,
    fontFamily: Platform.OS === 'ios' ? 'Courier New' : 'monospace',
    opacity: 0.7,
    marginBottom: 1,
  },
  terminalLogCategory: {
    fontSize: 11,
    fontFamily: Platform.OS === 'ios' ? 'Courier New' : 'monospace',
    lineHeight: 16,
    flexShrink: 1,
    flexWrap: 'wrap',
  },
  terminalLogMessage: {
    color: '#CDD9E5',
    fontSize: 11,
    fontFamily: Platform.OS === 'ios' ? 'Courier New' : 'monospace',
  },
  terminalEmptyText: {
    color: '#484F58',
    fontSize: 12,
    textAlign: 'center',
    paddingVertical: 24,
    fontStyle: 'italic',
  },
  tabContainer: {
    flexDirection: 'row',
    backgroundColor: 'rgba(255, 255, 255, 0.03)',
    borderRadius: 12,
    padding: 4,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.05)',
  },
  tabButton: {
    flex: 1,
    paddingVertical: 10,
    alignItems: 'center',
    borderRadius: 8,
  },
  tabButtonActive: {
    backgroundColor: '#3B82F6',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
  },
  tabButtonText: {
    color: '#94A3B8',
    fontSize: 11,
    fontWeight: '600',
  },
  tabButtonTextActive: {
    color: '#FFFFFF',
    fontWeight: 'bold',
  },
  input: {
    backgroundColor: 'rgba(255, 255, 255, 0.03)',
    borderColor: 'rgba(255, 255, 255, 0.08)',
    borderWidth: 1,
    borderRadius: 8,
    color: '#F8FAFC',
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 14,
    marginBottom: 12,
  },
  label: {
    color: '#94A3B8',
    fontSize: 12,
    fontWeight: '700',
    marginBottom: 6,
    marginTop: 4,
  },
  modalContent: {
    backgroundColor: '#0D1117',
    borderColor: 'rgba(255,255,255,0.1)',
    borderWidth: 1,
    borderRadius: 16,
    padding: 20,
    width: '92%',
    maxHeight: '85%',
    flexShrink: 1,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#F8FAFC',
    marginBottom: 16,
  },
  chipContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginBottom: 12,
  },
  tagChip: {
    backgroundColor: 'rgba(59, 130, 246, 0.12)',
    borderColor: '#3B82F655',
    borderWidth: 1,
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  tagChipText: {
    color: '#60A5FA',
    fontSize: 10,
    fontWeight: 'bold',
  },
  absoluteOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.6)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 9999,
  },
});

export default styles;
